### ISSUE TITLE
Image name with whitespace

### ISSUE THREAD

**Issue by dev4me** [cbopp-art/lightcase#41]
Thanks for this great plugin!!

I have some problems with filenames.
If an image filename includes a whitespace, the url opened by lightcase is wrong.

The link:
```html
<a class="lightcase" data-rel="lightcase" href="http://myserver/image 1.jpg">
    <img href="http://myserver/thumb 1.jpg" />
</a>
```
Will try to load:
```
http://myserver/image
```

**Comment by dev4me** [comment]
Thanks, I fixed it in my project. ( replacing to %20 )
I think I was just getting lazy not checking these things anymore because in most cases it just works fine.

**Comment by zymos** [comment]
There is still a problem with spaces.  I use php's urlencode to convert spaces to "%20", and it still fails to work.  I created a page to show the problem.
http://www.happytrees.org/tmp/tmp/test2.php
thanks
