### ISSUE TITLE
Images aren't loaded when desktop browser view is zoomed out

### ISSUE THREAD

**Issue by szaqal83** [cbopp-art/lightcase#43]
If browser view (on desktop) is zoomed out images aren't loaded, after some investigation I found that url is not being set at all in function `_determineUrl()`, I've added some logging and device pixel ratio was 0.89 and src.density was 1 so condition `_self._devicePixelRatio() >= src.density` is never true. Is it intended?

**Comment by cbopp-art** [comment]
Did you add a default source at the very beginning of the attribute and without defining viewport width or pixel ratio?
```data-lc-href="path/to/media2_default.jpg, path/to/media2_small.jpg 320w, path/to/media2_small_2x.jpg 320w 2x"```

**Comment by szaqal83** [comment]
Now I did but I don't know if I did it right, my setup is:
```
jQuery("a[rel^=lightcase]").lightcase({
			attr: "rel",
			showTitle: false,
			showCaption: false,
			showSequenceInfo: false,
			swipe: true
		});
```
viewport tag:
```
<meta content="width=device-width, initial-scale=1.0" name="viewport">
```
and sample html for image:
```
<a lc-href="path/to/media2_small.jpg, path/to/media2_small.jpg 320w, path/to/media2_small.jpg 320w 2x" rel="lightcase:2421" href="path/to/media2_small.jpg">
<img class="attachment-post-thumbnail size-post-thumbnail wp-post-image" width="180" height="125" alt="1885_img_0056" src="path/to/media2_small.jpg">
</a>
```

**Comment by cbopp-art** [comment]
attribute name must be ```lc-data-href``` not ```lc-href``` and also use ```data-rel```. Else it looks good.

**Comment by szaqal83** [comment]
I've to use rel but for testing I've changed my setup as You wrote, now it is:
```
jQuery("a[data-rel^=lightcase]").lightcase({
			showTitle: false,
			showCaption: false,
			showSequenceInfo: false,
			swipe: true
		});
```
<a lc-data-href="path/to/media2_small.jpg, path/to/media2_small.jpg 320w, path/to/media2_small.jpg 320w 2x" data-rel="lightcase:2421" href="path/to/media2_small.jpg">
<img class="attachment-post-thumbnail size-post-thumbnail wp-post-image" width="180" height="125" alt="1885_img_0056" src="path/to/media2_small.jpg">
</a>
```
but still doesn't work (earlier You wrote data-lc-href and now lc-data-href), and I found some inconsistency in doc's there is:
```Note: Sources are delimited using spaces. (since v2.3.0)```
but code sample shows commas:
```
<a href="" data-lc-href="path/to/media1_small.jpg, path/to/media1_large.jpg 2x" data-rel="lightcase">Your link description or thumb</a>
```
which is correct spaces or commas?

**Comment by cbopp-art** [comment]
Sorry, ```data-lc-href```of course. Because ```data-``` is a valid prefix for custom tag attributes.
Error in documentation is corrected. Thanks!

Comma is correct.

**Comment by szaqal83** [comment]
Ok, fixed my setup but still doesn't work because of this condition:
```
if (
					// Check density
					_self._devicePixelRatio() >= src.density &&
					src.density >= density &&
					// Check viewport width
					_self._matchMedia()('screen and (min-width:' + src.width + 'px)') &&
					src.width >= width
				) {
					width = src.width;
					density = src.density;
					url = src.url;
				}
```
it looks so, when I zoom out browser view device pixel ratio is:
```
0.89
```
so I've tried to set data-lc-href like so:
```
lc-data-href="path/to/media2_small.jpg, path/to/media2_small.jpg 0.1x
```
which results that:
```
_self._devicePixelRatio() (0.89) >= src.density (0.1)
```
is passed but second checking:
```
src.density (0.1) >= density (1 - hardcoded)
```
fails :/

**Comment by cbopp-art** [comment]
Is it fixed if you set ```density = _self._devicePixelRatio();``` instead of value 1?

**Comment by szaqal83** [comment]
Unfortunately no because:
```
src.density (0.1) >= density (0.89)
```
still isn't true

**Comment by szaqal83** [comment]
Perhaps this would do the job:
```
$.each(dataUrl, function (index, src) {

				width = src.width;
				density = src.density;
				url = src.url;
				
				if (
					// Check density
					_self._devicePixelRatio() >= src.density &&
					src.density >= density &&
					// Check viewport width
					_self._matchMedia()('screen and (min-width:' + src.width + 'px)') &&
					src.width >= width
				) {
					width = src.width;
					density = src.density;
					url = src.url;
				}
			});
```
url, density and width is always being set.

**Comment by cbopp-art** [comment]
Tried to reproduce the issue you have.
The only proper solution I actually see is to set default density to ```0``` instead of ```1``` in the following code lines:
https://github.com/cbopp-art/lightcase/blob/master/src/js/lightcase.js#L295
https://github.com/cbopp-art/lightcase/blob/master/src/js/lightcase.js#L329

**Comment by szaqal83** [comment]
Perhaps would it be even better to give user this oportinity, give it a value based on a config property? initDensity perhaps?

**Comment by cbopp-art** [comment]
Hmm, I think this should be fix.
Right now, it only allows to have sources for density >= 1
If this default value is set to 0, it allows any possible density including float values less than 1.

**Comment by szaqal83** [comment]
Ok, when a release with this fix will be available?

**Comment by cbopp-art** [comment]
In the next few days.

**Comment by szaqal83** [comment]
Ok, thanks for help.

**Comment by cbopp-art** [comment]
Your welcome! Thanks for facing the issue.
We can leave this issue with status open and I will commit a fix referencing this issue id.
